/*
    CREADOR JAVIER GÓMEZ GALLEGOS
*/
package sistPrestamoRecursos.vista;

import javax.swing.JOptionPane;
import sistPrestamoRecursos.controlador.ControladorAmigos;
import sistPrestamoRecursos.controlador.ControladorPrestamos;
import sistPrestamoRecursos.controlador.ControladorRecursos;


/**
 *
 * @author javier
 */
public class Main extends javax.swing.JFrame {
    /**
     * Creates new form Test
     */

        
    public Main() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuGuardar = new javax.swing.JMenu();
        botonGuardarTodo = new javax.swing.JMenuItem();
        botonSalir = new javax.swing.JMenuItem();
        menuAmigos = new javax.swing.JMenu();
        botonNuevoAmigo = new javax.swing.JMenuItem();
        botonVerEliminarAmigo = new javax.swing.JMenuItem();
        botonListarAmigos = new javax.swing.JMenuItem();
        botonAmigosConPrestamos = new javax.swing.JMenuItem();
        menuRecursos = new javax.swing.JMenu();
        botonNuevo = new javax.swing.JMenu();
        botonRecursoSimple = new javax.swing.JMenuItem();
        botonRecursoCompuesto = new javax.swing.JMenuItem();
        botonVer = new javax.swing.JMenuItem();
        botonDarDeBaja = new javax.swing.JMenuItem();
        botonListado = new javax.swing.JMenu();
        botonTodosLosRecursos = new javax.swing.JMenuItem();
        botonRecursosDisponibles = new javax.swing.JMenuItem();
        menuPrestamos = new javax.swing.JMenu();
        botonNuevoPrestamo = new javax.swing.JMenuItem();
        botonDevolucion = new javax.swing.JMenuItem();
        botonListarPrestamos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de prestamos a mis amigos");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
        });

        menuGuardar.setText("Archivo");

        botonGuardarTodo.setText("Guardar todo");
        botonGuardarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarTodoActionPerformed(evt);
            }
        });
        menuGuardar.add(botonGuardarTodo);

        botonSalir.setText("Salir");
        botonSalir.setToolTipText("");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        menuGuardar.add(botonSalir);

        jMenuBar1.add(menuGuardar);

        menuAmigos.setText("Amigo");

        botonNuevoAmigo.setText("Nuevo amigo...");
        botonNuevoAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoAmigoActionPerformed(evt);
            }
        });
        menuAmigos.add(botonNuevoAmigo);

        botonVerEliminarAmigo.setText("Ver o Eliminar amigo...");
        botonVerEliminarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerEliminarAmigoActionPerformed(evt);
            }
        });
        menuAmigos.add(botonVerEliminarAmigo);

        botonListarAmigos.setText("Listar todos los amigos...");
        botonListarAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarAmigosActionPerformed(evt);
            }
        });
        menuAmigos.add(botonListarAmigos);

        botonAmigosConPrestamos.setText("Listar amigos con prestamos pendientes...");
        botonAmigosConPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAmigosConPrestamosActionPerformed(evt);
            }
        });
        menuAmigos.add(botonAmigosConPrestamos);

        jMenuBar1.add(menuAmigos);

        menuRecursos.setText("Recurso");

        botonNuevo.setText("Nuevo");

        botonRecursoSimple.setText("Recurso simple");
        botonRecursoSimple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecursoSimpleActionPerformed(evt);
            }
        });
        botonNuevo.add(botonRecursoSimple);

        botonRecursoCompuesto.setText("Recurso compuesto");
        botonRecursoCompuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecursoCompuestoActionPerformed(evt);
            }
        });
        botonNuevo.add(botonRecursoCompuesto);

        menuRecursos.add(botonNuevo);

        botonVer.setText("Ver");
        botonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerActionPerformed(evt);
            }
        });
        menuRecursos.add(botonVer);

        botonDarDeBaja.setText("Dar de baja");
        botonDarDeBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDarDeBajaActionPerformed(evt);
            }
        });
        menuRecursos.add(botonDarDeBaja);

        botonListado.setText("Listado");

        botonTodosLosRecursos.setText("Todos los recursos");
        botonTodosLosRecursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTodosLosRecursosActionPerformed(evt);
            }
        });
        botonListado.add(botonTodosLosRecursos);

        botonRecursosDisponibles.setText("Recursos disponibles para prestamo");
        botonRecursosDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRecursosDisponiblesActionPerformed(evt);
            }
        });
        botonListado.add(botonRecursosDisponibles);

        menuRecursos.add(botonListado);

        jMenuBar1.add(menuRecursos);

        menuPrestamos.setText("Prestamo");

        botonNuevoPrestamo.setText("Nuevo prestamo");
        botonNuevoPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoPrestamoActionPerformed(evt);
            }
        });
        menuPrestamos.add(botonNuevoPrestamo);

        botonDevolucion.setText("Devolucion");
        botonDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolucionActionPerformed(evt);
            }
        });
        menuPrestamos.add(botonDevolucion);

        botonListarPrestamos.setText("Listar todos los prestamos");
        botonListarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonListarPrestamosActionPerformed(evt);
            }
        });
        menuPrestamos.add(botonListarPrestamos);

        jMenuBar1.add(menuPrestamos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarTodoActionPerformed
        // TODO add your handling code here:
        ControladorPrestamos con= ControladorPrestamos.getInstancia();
        con.guardarDatosSistema();
    }//GEN-LAST:event_botonGuardarTodoActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        int resp=JOptionPane.showConfirmDialog(null, "¿Desea guardar antes de salir?","ALERTA", JOptionPane.YES_NO_OPTION);
        if(resp==0){
            ControladorPrestamos con= ControladorPrestamos.getInstancia();
            con.guardarDatosSistema();
        }
        dispose();
    }//GEN-LAST:event_botonSalirActionPerformed

    private void botonNuevoAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoAmigoActionPerformed
        // TODO add your handling code here:
        NuevoAmigo ventana=new NuevoAmigo();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonNuevoAmigoActionPerformed

    private void botonVerEliminarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerEliminarAmigoActionPerformed
        // TODO add your handling code here:
        if(ControladorAmigos.getInstancia().listarAmigos()!=null){
            Ver ventana=new Ver();
            ventana.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No existen amigos en la agenda", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonVerEliminarAmigoActionPerformed

    private void botonListarAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarAmigosActionPerformed
        // TODO add your handling code here:
        String [][] data=ControladorAmigos.getInstancia().listarAmigosSinPretamoPendiente();
        if(data!= null){
            Listado ventana=new Listado();
            ventana.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No existen amigos sin prestamos ", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonListarAmigosActionPerformed

    private void botonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerActionPerformed
        // TODO add your handling code here:
        if(ControladorRecursos.getInstancia().listarRecursos()!=null){
            BuscarRecurso ventna=new BuscarRecurso();
            ventna.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No existen recursos en el catalogo", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonVerActionPerformed

    private void botonRecursoSimpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecursoSimpleActionPerformed
        // TODO add your handling code here:
        RecursoSimple ventana=new RecursoSimple();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_botonRecursoSimpleActionPerformed

    private void botonDarDeBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDarDeBajaActionPerformed
        // TODO add your handling code here:
        if(ControladorRecursos.getInstancia().listarRecursos()!=null){
            DarBaja ven= new DarBaja();
            ven.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No existen recursos en el catalogo", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonDarDeBajaActionPerformed

    private void botonTodosLosRecursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTodosLosRecursosActionPerformed
        // TODO add your handling code here:
        String [][] data=ControladorRecursos.getInstancia().listarRecursos();
        if(data!=null){
            ListaRecursos ventana=new ListaRecursos();
            ventana.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No existen recursos", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonTodosLosRecursosActionPerformed

    private void botonRecursosDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecursosDisponiblesActionPerformed
        // TODO add your handling code here:
        String [][] data=ControladorRecursos.getInstancia().listarRecursosActivosNoPrestados();
        if(data!=null){
            RecursoDisponibleParaPrestamos ventana=new RecursoDisponibleParaPrestamos();
            ventana.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No hay recursos para prestar", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_botonRecursosDisponiblesActionPerformed

    private void botonRecursoCompuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecursoCompuestoActionPerformed
        // TODO add your handling code here:
        String [][] data=ControladorRecursos.getInstancia().listarRecursosDisponibles();
        if(data!=null){
            RecursoCompuesto ventana=new RecursoCompuesto();
            ventana.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No hay recursos para crear recursos compuestos", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_botonRecursoCompuestoActionPerformed

    private void botonNuevoPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoPrestamoActionPerformed
        // TODO add your handling code here:
        String [][] data1=ControladorRecursos.getInstancia().listarRecursosActivosNoPrestados();
        String [][] data2=ControladorAmigos.getInstancia().listarAmigosSinPretamoPendiente();
        if(data1!= null && data2!= null){
            NuevoPrestamo ventana=new NuevoPrestamo();
            ventana.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No existen amigos/recursos para realizar prestamos", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonNuevoPrestamoActionPerformed

    private void botonDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolucionActionPerformed
        // TODO add your handling code here:
        String [][] data1=ControladorPrestamos.getInstancia().listarPrestamosPendientes();
        if(data1!= null){
            VentanaDevolucion ventana=new VentanaDevolucion();
            ventana.setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No existen prestamos pendientes", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonDevolucionActionPerformed

    private void botonListarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonListarPrestamosActionPerformed
        // TODO add your handling code here
        String [][] data= ControladorPrestamos.getInstancia().listarPrestamos();
        if(data!=null){
            new ListaPrestamos().setVisible(true);
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "No existen prestamos en el sistema", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_botonListarPrestamosActionPerformed

    private void botonAmigosConPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAmigosConPrestamosActionPerformed
        // TODO add your handling code here:
        String [][] data=ControladorAmigos.getInstancia().listarAmigosConPrestamoPendiente();
        if(data==null){
            JOptionPane.showMessageDialog(null, "No hay amigos con prestamos pendientes", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }else{
            AmigosPrestamosPendiente ventana=new AmigosPrestamosPendiente();
            ventana.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_botonAmigosConPrestamosActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int resp=JOptionPane.showConfirmDialog(null, "¿Desea guardar antes de salir?","ALERTA", JOptionPane.YES_NO_OPTION);
        if(resp==0){
            ControladorPrestamos con= ControladorPrestamos.getInstancia();
            con.guardarDatosSistema();
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowDeactivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        }
        
        );
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem botonAmigosConPrestamos;
    private javax.swing.JMenuItem botonDarDeBaja;
    private javax.swing.JMenuItem botonDevolucion;
    private javax.swing.JMenuItem botonGuardarTodo;
    private javax.swing.JMenu botonListado;
    private javax.swing.JMenuItem botonListarAmigos;
    private javax.swing.JMenuItem botonListarPrestamos;
    private javax.swing.JMenu botonNuevo;
    private javax.swing.JMenuItem botonNuevoAmigo;
    private javax.swing.JMenuItem botonNuevoPrestamo;
    private javax.swing.JMenuItem botonRecursoCompuesto;
    private javax.swing.JMenuItem botonRecursoSimple;
    private javax.swing.JMenuItem botonRecursosDisponibles;
    private javax.swing.JMenuItem botonSalir;
    private javax.swing.JMenuItem botonTodosLosRecursos;
    private javax.swing.JMenuItem botonVer;
    private javax.swing.JMenuItem botonVerEliminarAmigo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAmigos;
    private javax.swing.JMenu menuGuardar;
    private javax.swing.JMenu menuPrestamos;
    private javax.swing.JMenu menuRecursos;
    // End of variables declaration//GEN-END:variables
}
